# Generated by Django 5.0.6 on 2024-05-25 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_user_coupon_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='group title')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is group pinned?')),
                ('access_password', models.CharField(blank=True, help_text='optional', max_length=128, null=True, verbose_name='access password')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner of the group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-date_added', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is group pinned?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='memberships', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.CreateModel(
            name='ShopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is shop pinned?')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='group')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop', verbose_name='shop')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='shops',
            field=models.ManyToManyField(related_name='groups', through='groups.ShopGroup', to='core.shop', verbose_name='shops'),
        ),
    ]
