# Generated by Django 5.0.6 on 2024-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_invitation_invitation_unique_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='in_group',
            field=models.BooleanField(default=False, verbose_name='is recipient in group?'),
        ),
    ]
