# Generated by Django 5.0.6 on 2024-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_invitation_in_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='in_group',
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='is accepted?'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='is processed?'),
        ),
    ]
