# Generated by Django 5.0.6 on 2024-05-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_invitation_in_group_invitation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date_added', 'title'], 'permissions': [('invite_user', 'Can invite user'), ('remove_user', 'Can remove user'), ('add_shop', 'Can add shop'), ('remove_shop', 'Can remove shop')], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
