# Generated by Django 5.0.6 on 2024-05-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='barcode',
            field=models.CharField(max_length=200, verbose_name='coupon barcode'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(blank=True, help_text='can be null', max_length=100, null=True, verbose_name='coupon title'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner of the shop'),
        ),
    ]
