# Generated by Django 5.0.6 on 2024-05-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user',
            new_name='owner',
        ),
    ]
