# Generated by Django 5.0.6 on 2024-06-01 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_coupon_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
