# Generated by Django 5.0.6 on 2024-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coupon_coupon_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-date_added', 'title'], 'permissions': [('share_coupon', 'Can share coupon'), ('unshare_coupon', 'Can unshare coupon')], 'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
    ]
