# Generated by Django 5.0.6 on 2024-06-01 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coupon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='coupon uuid'),
        ),
    ]
