# Generated by Django 5.0.6 on 2024-06-01 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_coupon_coupon_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_uuid',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='coupon uuid'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='shop uuid'),
        ),
    ]
