# Generated by Django 5.0.6 on 2024-06-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shop_is_on_marketplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-date_added', 'title'], 'permissions': [('upload_to_marketplace_shop', 'Can upload shop to marketplace'), ('remove_from_marketplace_shop', 'Can remove shop from marketplace')], 'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
    ]
