# Generated by Django 5.0.6 on 2024-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_shop', 'Can view a shop on the marketplace'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
