# Generated by Django 5.0.6 on 2024-06-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_shop_marketplace', 'Can view a shop on the marketplace'),)},
        ),
    ]
