# Generated by Django 5.0.6 on 2024-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_shop_marketplace', 'Can view a shop on the marketplace'), ('use_shop_from_marketplace', 'Can use a shop from the marketplace'))},
        ),
    ]
