services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registar_django
    command: sh -c "python3 manage.py migrate --noinput && 
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - registar_network
    
  db:
    image: mysql
    container_name: registar_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - registar_network

networks:
  registar_network: