services:
  django_gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registar_django
    command: sh -c "mkdir -p logs &&
                    touch persistance/local.py &&
                    python3 manage.py migrate --noinput && 
                    python3 manage.py initgroups --nooutput &&
                    django-admin compilemessages &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn --bind 0.0.0.0:8000 registar.wsgi"
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always