# Generated by Django 5.0.6 on 2024-05-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined', 'username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
